#ifndef VERSION_H
#define VERSION_H

#define ZEPHYROS_VERSION_MAJOR 0U
#define ZEPHYROS_VERSION_MINOR 1U
#define ZEPHYROS_VERSION_PATCH 0U
#define ZEPHYROS_VERSION_EPOCH 0U

#define ZEPHYROS_VERSION_TEXT "0.1.0"
#define ZEPHYROS_DISPLAY_NAME "ZephyrOS v0.1.0"

#endif
